// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogReadDirection selects whether to read from the end of the file (tail) or the start (head).
type LogReadDirection int32

const (
	LogReadDirection_LOG_READ_TAIL LogReadDirection = 0
	LogReadDirection_LOG_READ_HEAD LogReadDirection = 1
)

// Enum value maps for LogReadDirection.
var (
	LogReadDirection_name = map[int32]string{
		0: "LOG_READ_TAIL",
		1: "LOG_READ_HEAD",
	}
	LogReadDirection_value = map[string]int32{
		"LOG_READ_TAIL": 0,
		"LOG_READ_HEAD": 1,
	}
)

func (x LogReadDirection) Enum() *LogReadDirection {
	p := new(LogReadDirection)
	*p = x
	return p
}

func (x LogReadDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogReadDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (LogReadDirection) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x LogReadDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogReadDirection.Descriptor instead.
func (LogReadDirection) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

type WorkerMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_HeartbeatPong
	//	*WorkerMessage_Result
	//	*WorkerMessage_Register
	//	*WorkerMessage_JobLogResponse
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeatPong() *HeartbeatPong {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_HeartbeatPong); ok {
			return x.HeartbeatPong
		}
	}
	return nil
}

func (x *WorkerMessage) GetResult() *JobResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *WorkerRegistration {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetJobLogResponse() *JobLogResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_JobLogResponse); ok {
			return x.JobLogResponse
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_HeartbeatPong struct {
	HeartbeatPong *HeartbeatPong `protobuf:"bytes,2,opt,name=heartbeat_pong,json=heartbeatPong,proto3,oneof"`
}

type WorkerMessage_Result struct {
	Result *JobResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type WorkerMessage_Register struct {
	Register *WorkerRegistration `protobuf:"bytes,4,opt,name=register,proto3,oneof"`
}

type WorkerMessage_JobLogResponse struct {
	JobLogResponse *JobLogResponse `protobuf:"bytes,5,opt,name=job_log_response,json=jobLogResponse,proto3,oneof"`
}

func (*WorkerMessage_HeartbeatPong) isWorkerMessage_Payload() {}

func (*WorkerMessage_Result) isWorkerMessage_Payload() {}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_JobLogResponse) isWorkerMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_HeartbeatPing
	//	*ServerMessage_Assign
	//	*ServerMessage_Drain
	//	*ServerMessage_JobLogRequest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetHeartbeatPing() *HeartbeatPing {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_HeartbeatPing); ok {
			return x.HeartbeatPing
		}
	}
	return nil
}

func (x *ServerMessage) GetAssign() *JobAssignment {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *ServerMessage) GetDrain() *DrainSignal {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *ServerMessage) GetJobLogRequest() *JobLogRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_JobLogRequest); ok {
			return x.JobLogRequest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_HeartbeatPing struct {
	HeartbeatPing *HeartbeatPing `protobuf:"bytes,1,opt,name=heartbeat_ping,json=heartbeatPing,proto3,oneof"`
}

type ServerMessage_Assign struct {
	Assign *JobAssignment `protobuf:"bytes,2,opt,name=assign,proto3,oneof"`
}

type ServerMessage_Drain struct {
	Drain *DrainSignal `protobuf:"bytes,3,opt,name=drain,proto3,oneof"`
}

type ServerMessage_JobLogRequest struct {
	JobLogRequest *JobLogRequest `protobuf:"bytes,4,opt,name=job_log_request,json=jobLogRequest,proto3,oneof"`
}

func (*ServerMessage_HeartbeatPing) isServerMessage_Payload() {}

func (*ServerMessage_Assign) isServerMessage_Payload() {}

func (*ServerMessage_Drain) isServerMessage_Payload() {}

func (*ServerMessage_JobLogRequest) isServerMessage_Payload() {}

// JobLogRequest asks the worker to return up to `limit` complete lines from a job log file.
// TAIL: anchor_offset 0 = from EOF; anchor_offset X = read lines strictly before byte X.
// HEAD: anchor_offset 0 = from BOF; anchor_offset X = start reading at byte X.
type JobLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Direction     LogReadDirection       `protobuf:"varint,3,opt,name=direction,proto3,enum=worker.LogReadDirection" json:"direction,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	AnchorOffset  int64                  `protobuf:"varint,5,opt,name=anchor_offset,json=anchorOffset,proto3" json:"anchor_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLogRequest) Reset() {
	*x = JobLogRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLogRequest) ProtoMessage() {}

func (x *JobLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLogRequest.ProtoReflect.Descriptor instead.
func (*JobLogRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *JobLogRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *JobLogRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobLogRequest) GetDirection() LogReadDirection {
	if x != nil {
		return x.Direction
	}
	return LogReadDirection_LOG_READ_TAIL
}

func (x *JobLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *JobLogRequest) GetAnchorOffset() int64 {
	if x != nil {
		return x.AnchorOffset
	}
	return 0
}

type JobLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Lines         []string               `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	NextAnchor    int64                  `protobuf:"varint,3,opt,name=next_anchor,json=nextAnchor,proto3" json:"next_anchor,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLogResponse) Reset() {
	*x = JobLogResponse{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLogResponse) ProtoMessage() {}

func (x *JobLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLogResponse.ProtoReflect.Descriptor instead.
func (*JobLogResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *JobLogResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *JobLogResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *JobLogResponse) GetNextAnchor() int64 {
	if x != nil {
		return x.NextAnchor
	}
	return 0
}

func (x *JobLogResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *JobLogResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *JobLogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatPing) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MetricValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*MetricValue_I
	//	*MetricValue_F
	//	*MetricValue_S
	Kind          isMetricValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricValue) Reset() {
	*x = MetricValue{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricValue) ProtoMessage() {}

func (x *MetricValue) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricValue.ProtoReflect.Descriptor instead.
func (*MetricValue) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *MetricValue) GetKind() isMetricValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *MetricValue) GetI() int64 {
	if x != nil {
		if x, ok := x.Kind.(*MetricValue_I); ok {
			return x.I
		}
	}
	return 0
}

func (x *MetricValue) GetF() float64 {
	if x != nil {
		if x, ok := x.Kind.(*MetricValue_F); ok {
			return x.F
		}
	}
	return 0
}

func (x *MetricValue) GetS() string {
	if x != nil {
		if x, ok := x.Kind.(*MetricValue_S); ok {
			return x.S
		}
	}
	return ""
}

type isMetricValue_Kind interface {
	isMetricValue_Kind()
}

type MetricValue_I struct {
	I int64 `protobuf:"varint,1,opt,name=i,proto3,oneof"`
}

type MetricValue_F struct {
	F float64 `protobuf:"fixed64,2,opt,name=f,proto3,oneof"`
}

type MetricValue_S struct {
	S string `protobuf:"bytes,3,opt,name=s,proto3,oneof"`
}

func (*MetricValue_I) isMetricValue_Kind() {}

func (*MetricValue_F) isMetricValue_Kind() {}

func (*MetricValue_S) isMetricValue_Kind() {}

type HeartbeatPong struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metrics       map[string]*MetricValue `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatPong) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatPong) GetMetrics() map[string]*MetricValue {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatPong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WorkerRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []string               `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	Concurrency   int32                  `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRegistration) Reset() {
	*x = WorkerRegistration{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistration) ProtoMessage() {}

func (x *WorkerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistration.ProtoReflect.Descriptor instead.
func (*WorkerRegistration) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerRegistration) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *WorkerRegistration) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type JobAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeoutSec    int32                  `protobuf:"varint,5,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignment) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *JobAssignment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobAssignment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JobAssignment) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

// ContainerJobSpec describes a job that runs inside a Docker container.
// For type "container", JobAssignment.payload is JSON matching this message.
type ContainerJobSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceRepository string                 `protobuf:"bytes,1,opt,name=source_repository,json=sourceRepository,proto3" json:"source_repository,omitempty"`                                                                  // optional; https GitHub URL when set
	Runtime          string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`                                                                                                            // Docker image name, e.g. python:3.12, node:20
	RequestParams    map[string]string      `protobuf:"bytes,3,rep,name=request_params,json=requestParams,proto3" json:"request_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // user inputs -> env vars in container
	Command          string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`                                                                                                            // bash script to run inside the container
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerJobSpec) Reset() {
	*x = ContainerJobSpec{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerJobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerJobSpec) ProtoMessage() {}

func (x *ContainerJobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerJobSpec.ProtoReflect.Descriptor instead.
func (*ContainerJobSpec) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerJobSpec) GetSourceRepository() string {
	if x != nil {
		return x.SourceRepository
	}
	return ""
}

func (x *ContainerJobSpec) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ContainerJobSpec) GetRequestParams() map[string]string {
	if x != nil {
		return x.RequestParams
	}
	return nil
}

func (x *ContainerJobSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type JobResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error            string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ElapsedMs        int64                  `protobuf:"varint,4,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	LogFile          string                 `protobuf:"bytes,5,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	ExecutionLogFile string                 `protobuf:"bytes,6,opt,name=execution_log_file,json=executionLogFile,proto3" json:"execution_log_file,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobResult) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *JobResult) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *JobResult) GetExecutionLogFile() string {
	if x != nil {
		return x.ExecutionLogFile
	}
	return ""
}

type DrainSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainSignal) Reset() {
	*x = DrainSignal{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainSignal) ProtoMessage() {}

func (x *DrainSignal) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainSignal.ProtoReflect.Descriptor instead.
func (*DrainSignal) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x06worker\"\xa2\x02\n" +
	"\rWorkerMessage\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12>\n" +
	"\x0eheartbeat_pong\x18\x02 \x01(\v2\x15.worker.HeartbeatPongH\x00R\rheartbeatPong\x12+\n" +
	"\x06result\x18\x03 \x01(\v2\x11.worker.JobResultH\x00R\x06result\x128\n" +
	"\bregister\x18\x04 \x01(\v2\x1a.worker.WorkerRegistrationH\x00R\bregister\x12B\n" +
	"\x10job_log_response\x18\x05 \x01(\v2\x16.worker.JobLogResponseH\x00R\x0ejobLogResponseB\t\n" +
	"\apayload\"\xf9\x01\n" +
	"\rServerMessage\x12>\n" +
	"\x0eheartbeat_ping\x18\x01 \x01(\v2\x15.worker.HeartbeatPingH\x00R\rheartbeatPing\x12/\n" +
	"\x06assign\x18\x02 \x01(\v2\x15.worker.JobAssignmentH\x00R\x06assign\x12+\n" +
	"\x05drain\x18\x03 \x01(\v2\x13.worker.DrainSignalH\x00R\x05drain\x12?\n" +
	"\x0fjob_log_request\x18\x04 \x01(\v2\x15.worker.JobLogRequestH\x00R\rjobLogRequestB\t\n" +
	"\apayload\"\xb8\x01\n" +
	"\rJobLogRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x126\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x18.worker.LogReadDirectionR\tdirection\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12#\n" +
	"\ranchor_offset\x18\x05 \x01(\x03R\fanchorOffset\"\xb4\x01\n" +
	"\x0eJobLogResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05lines\x18\x02 \x03(\tR\x05lines\x12\x1f\n" +
	"\vnext_anchor\x18\x03 \x01(\x03R\n" +
	"nextAnchor\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"-\n" +
	"\rHeartbeatPing\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"E\n" +
	"\vMetricValue\x12\x0e\n" +
	"\x01i\x18\x01 \x01(\x03H\x00R\x01i\x12\x0e\n" +
	"\x01f\x18\x02 \x01(\x01H\x00R\x01f\x12\x0e\n" +
	"\x01s\x18\x03 \x01(\tH\x00R\x01sB\x06\n" +
	"\x04kind\"\xd4\x01\n" +
	"\rHeartbeatPong\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12<\n" +
	"\ametrics\x18\x02 \x03(\v2\".worker.HeartbeatPong.MetricsEntryR\ametrics\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1aO\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.worker.MetricValueR\x05value:\x028\x01\"N\n" +
	"\x12WorkerRegistration\x12\x16\n" +
	"\x06queues\x18\x01 \x03(\tR\x06queues\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x05R\vconcurrency\"\x8b\x01\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1f\n" +
	"\vtimeout_sec\x18\x05 \x01(\x05R\n" +
	"timeoutSec\"\x89\x02\n" +
	"\x10ContainerJobSpec\x12+\n" +
	"\x11source_repository\x18\x01 \x01(\tR\x10sourceRepository\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12R\n" +
	"\x0erequest_params\x18\x03 \x03(\v2+.worker.ContainerJobSpec.RequestParamsEntryR\rrequestParams\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x1a@\n" +
	"\x12RequestParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x04 \x01(\x03R\telapsedMs\x12\x19\n" +
	"\blog_file\x18\x05 \x01(\tR\alogFile\x12,\n" +
	"\x12execution_log_file\x18\x06 \x01(\tR\x10executionLogFile\"\r\n" +
	"\vDrainSignal*8\n" +
	"\x10LogReadDirection\x12\x11\n" +
	"\rLOG_READ_TAIL\x10\x00\x12\x11\n" +
	"\rLOG_READ_HEAD\x10\x012L\n" +
	"\rWorkerService\x12;\n" +
	"\aConnect\x12\x15.worker.WorkerMessage\x1a\x15.worker.ServerMessage(\x010\x01B\x1eZ\x1cgithub.com/lute/proto;workerb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_worker_proto_goTypes = []any{
	(LogReadDirection)(0),      // 0: worker.LogReadDirection
	(*WorkerMessage)(nil),      // 1: worker.WorkerMessage
	(*ServerMessage)(nil),      // 2: worker.ServerMessage
	(*JobLogRequest)(nil),      // 3: worker.JobLogRequest
	(*JobLogResponse)(nil),     // 4: worker.JobLogResponse
	(*HeartbeatPing)(nil),      // 5: worker.HeartbeatPing
	(*MetricValue)(nil),        // 6: worker.MetricValue
	(*HeartbeatPong)(nil),      // 7: worker.HeartbeatPong
	(*WorkerRegistration)(nil), // 8: worker.WorkerRegistration
	(*JobAssignment)(nil),      // 9: worker.JobAssignment
	(*ContainerJobSpec)(nil),   // 10: worker.ContainerJobSpec
	(*JobResult)(nil),          // 11: worker.JobResult
	(*DrainSignal)(nil),        // 12: worker.DrainSignal
	nil,                        // 13: worker.HeartbeatPong.MetricsEntry
	nil,                        // 14: worker.ContainerJobSpec.RequestParamsEntry
}
var file_worker_proto_depIdxs = []int32{
	7,  // 0: worker.WorkerMessage.heartbeat_pong:type_name -> worker.HeartbeatPong
	11, // 1: worker.WorkerMessage.result:type_name -> worker.JobResult
	8,  // 2: worker.WorkerMessage.register:type_name -> worker.WorkerRegistration
	4,  // 3: worker.WorkerMessage.job_log_response:type_name -> worker.JobLogResponse
	5,  // 4: worker.ServerMessage.heartbeat_ping:type_name -> worker.HeartbeatPing
	9,  // 5: worker.ServerMessage.assign:type_name -> worker.JobAssignment
	12, // 6: worker.ServerMessage.drain:type_name -> worker.DrainSignal
	3,  // 7: worker.ServerMessage.job_log_request:type_name -> worker.JobLogRequest
	0,  // 8: worker.JobLogRequest.direction:type_name -> worker.LogReadDirection
	13, // 9: worker.HeartbeatPong.metrics:type_name -> worker.HeartbeatPong.MetricsEntry
	14, // 10: worker.ContainerJobSpec.request_params:type_name -> worker.ContainerJobSpec.RequestParamsEntry
	6,  // 11: worker.HeartbeatPong.MetricsEntry.value:type_name -> worker.MetricValue
	1,  // 12: worker.WorkerService.Connect:input_type -> worker.WorkerMessage
	2,  // 13: worker.WorkerService.Connect:output_type -> worker.ServerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_HeartbeatPong)(nil),
		(*WorkerMessage_Result)(nil),
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_JobLogResponse)(nil),
	}
	file_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_HeartbeatPing)(nil),
		(*ServerMessage_Assign)(nil),
		(*ServerMessage_Drain)(nil),
		(*ServerMessage_JobLogRequest)(nil),
	}
	file_worker_proto_msgTypes[5].OneofWrappers = []any{
		(*MetricValue_I)(nil),
		(*MetricValue_F)(nil),
		(*MetricValue_S)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
