// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file. Run `make proto` or `./scripts/generate-proto.sh` to generate the actual code.
//
// To generate the real proto code, you need:
// 1. Install protoc: https://grpc.io/docs/protoc-installation/
// 2. Install Go plugins:
//    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
// 3. Run: make proto

package agent

