// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a placeholder file. Run `make proto` or `./scripts/generate-proto.sh` to generate the actual code.
//
// To generate the real proto code, you need:
// 1. Install protoc: https://grpc.io/docs/protoc-installation/
// 2. Install Go plugins:
//    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
// 3. Run: make proto

package agent

import (
	"context"
	"fmt"
	"google.golang.org/grpc"
)

// This is a placeholder. The real implementation will be generated.
type AgentServiceClient interface {
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	UpdateMachineStatus(ctx context.Context, in *UpdateMachineStatusRequest, opts ...grpc.CallOption) (*UpdateMachineStatusResponse, error)
	GetMachineConfig(ctx context.Context, in *GetMachineConfigRequest, opts ...grpc.CallOption) (*GetMachineConfigResponse, error)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (AgentService_StreamLogsClient, error)
}

type AgentServiceServer interface {
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	UpdateMachineStatus(context.Context, *UpdateMachineStatusRequest) (*UpdateMachineStatusResponse, error)
	GetMachineConfig(context.Context, *GetMachineConfigRequest) (*GetMachineConfigResponse, error)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	StreamLogs(*StreamLogsRequest, AgentService_StreamLogsServer) error
}

type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, nil
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, nil
}
func (UnimplementedAgentServiceServer) UpdateMachineStatus(context.Context, *UpdateMachineStatusRequest) (*UpdateMachineStatusResponse, error) {
	return nil, nil
}
func (UnimplementedAgentServiceServer) GetMachineConfig(context.Context, *GetMachineConfigRequest) (*GetMachineConfigResponse, error) {
	return nil, nil
}
func (UnimplementedAgentServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, nil
}
func (UnimplementedAgentServiceServer) StreamLogs(*StreamLogsRequest, AgentService_StreamLogsServer) error {
	return nil
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {}

// NewAgentServiceClient creates a new client for AgentService
func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc: cc}
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func (c *agentServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	return nil, fmt.Errorf("placeholder: proto files not generated")
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	return nil, fmt.Errorf("placeholder: proto files not generated")
}

func (c *agentServiceClient) UpdateMachineStatus(ctx context.Context, in *UpdateMachineStatusRequest, opts ...grpc.CallOption) (*UpdateMachineStatusResponse, error) {
	return nil, fmt.Errorf("placeholder: proto files not generated")
}

func (c *agentServiceClient) GetMachineConfig(ctx context.Context, in *GetMachineConfigRequest, opts ...grpc.CallOption) (*GetMachineConfigResponse, error) {
	return nil, fmt.Errorf("placeholder: proto files not generated")
}

func (c *agentServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	return nil, fmt.Errorf("placeholder: proto files not generated")
}

func (c *agentServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (AgentService_StreamLogsClient, error) {
	return nil, fmt.Errorf("placeholder: proto files not generated")
}

type AgentService_StreamLogsClient interface {
	Recv() (*LogMessage, error)
	grpc.ClientStream
}

type RegisterAgentRequest struct {
	AgentId   string
	MachineId string
	Version   string
	IpAddress string
	Metadata map[string]string
}

type RegisterAgentResponse struct {
	Success      bool
	Message      string
	ServerVersion string
}

type HeartbeatRequest struct {
	AgentId string
	Status  string
	Metrics map[string]string
}

type HeartbeatResponse struct {
	Success   bool
	Timestamp int64
}

type UpdateMachineStatusRequest struct {
	AgentId   string
	MachineId string
	Status    string
	Message   string
}

type UpdateMachineStatusResponse struct {
	Success bool
	Message string
}

type GetMachineConfigRequest struct {
	AgentId   string
	MachineId string
}

type GetMachineConfigResponse struct {
	Success bool
	Config  map[string]string
	Message string
}

type ExecuteCommandRequest struct {
	AgentId   string
	MachineId string
	Command   string
	Args      []string
	Env       map[string]string
}

type ExecuteCommandResponse struct {
	Success  bool
	Output   string
	ExitCode int32
	Error    string
}

type StreamLogsRequest struct {
	AgentId   string
	MachineId string
	Level     string
}

type LogMessage struct {
	Level     string
	Message   string
	Timestamp int64
	Source    string
}

type AgentService_StreamLogsServer interface {
	Send(*LogMessage) error
	grpc.ServerStream
}

