/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the server version
         * @description Needs no API key, so a client can check the server before it has one.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who am I
         * @description The key that made the request, and who it acts as. A service key acts as itself, so `user`
         *     is left out. Call it to check a key before saving it.
         */
        get: operations["whoAmI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description Every job definition, each with the newest run the key can see.
         */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The job's `slug`.
                 * @example web-release
                 */
                slug: components["parameters"]["JobSlug"];
            };
            cookie?: never;
        };
        /**
         * Get a job
         * @description The job and its parameter schema: types, defaults and options, which is what a client needs
         *     to know what to pass. A `secret` parameter is listed, but nothing about its value is.
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{slug}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The job's `slug`.
                 * @example web-release
                 */
                slug: components["parameters"]["JobSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a run of a job
         * @description Runs the definition as it is, with `params` keyed by parameter name. Core validates them as
         *     the panel does: a missing required value or a bad one answers `400` and names the parameter
         *     in `error.fields`. Answers `201` with the new run, or `200` with the earlier one when the
         *     `Idempotency-Key` was used before.
         */
        post: operations["startJobRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs
         * @description Runs the key can see, newest first, filtered and paged. An account key sees its user's runs
         *     and those service keys started; a service key sees every run.
         */
        get: operations["listRuns"];
        put?: never;
        /**
         * Create a run
         * @description Puts a job on a queue. The first worker that serves the queue and has every label in
         *     `selector` leases it. Answers `201` with the new run, or `200` with the existing one when
         *     `idempotency_key` was used before.
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The run's `id`, or a prefix of it of at least 8 characters.
                 * @example 66fb1c2d
                 */
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /**
         * Get a run
         * @description The run's current state. A short id that matches more than one run answers `400`.
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        /**
         * Cancel a run
         * @description Cancels a run that no worker has taken yet. It ends with status `dead` and error
         *     `cancelled`. A run that already started answers `409`.
         */
        delete: operations["cancelRun"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The run's `id`, or a prefix of it of at least 8 characters.
                 * @example 66fb1c2d
                 */
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a run
         * @description Queues the run again from its first attempt, with the same payload.
         */
        post: operations["retryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The run's `id`, or a prefix of it of at least 8 characters.
                 * @example 66fb1c2d
                 */
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /**
         * Read a run's log
         * @description A page of the log. Logs stay on the worker that ran the job, so core asks that worker for
         *     them: an offline worker answers `503`.
         */
        get: operations["getRunLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workers
         * @description Your workers, optionally only those with the given labels.
         */
        get: operations["listWorkers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/connected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List connected workers
         * @description Workers with a live connection to this core, and how busy they are.
         */
        get: operations["listConnectedWorkers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get install details
         * @description The gRPC address and image a new worker's `docker run` needs.
         */
        get: operations["getInstallInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        /** Get a worker */
        get: operations["getWorker"];
        /**
         * Update a worker
         * @description Renames or re-describes a worker. Fields left out stay as they are.
         */
        put: operations["updateWorker"];
        post?: never;
        /**
         * Delete a worker
         * @description A connected worker finishes its running jobs, then core removes it and the agent stops its
         *     own container (`202`). A worker that is not connected is removed at once (`200`).
         */
        delete: operations["deleteWorker"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        /**
         * Get live status
         * @description A lighter read than the full worker, for polling.
         */
        get: operations["getWorkerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/{id}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        /** Get labels */
        get: operations["getWorkerLabels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set labels
         * @description Replaces the worker's labels. Runs waiting for a `selector` this worker now matches are
         *     dispatched right away.
         */
        patch: operations["setWorkerLabels"];
        trace?: never;
    };
    "/workers/{id}/re-enable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-enable a worker
         * @description Moves a `dead` worker back to `pending` so its agent may connect again.
         */
        post: operations["reEnableWorker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        /**
         * List commands
         * @description The worker's 50 most recent commands.
         */
        get: operations["listCommands"];
        put?: never;
        /**
         * Send a command
         * @description Queues a command for the worker's agent. The worker must have connected at least once.
         */
        post: operations["sendCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/command-results/{commandId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description `command_id` from Send a command.
                 * @example 66fa2b0c1d2e3f4a5b6c7d8e
                 */
                commandId: string;
            };
            cookie?: never;
        };
        /** Get a command's result */
        get: operations["getCommandResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tokens */
        get: operations["listTokens"];
        put?: never;
        /**
         * Create a token
         * @description The plaintext `token` is in this response only; core keeps a hash.
         */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The token's `id`.
                 * @example 66fa2c7d8e9f0a1b2c3d4e5f
                 */
                tokenId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a token
         * @description Stops new registrations with it. Workers that already registered keep working.
         */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Version: {
            /** @description The core release, or `dev`. */
            version: string;
            /** @description Goes up when the public API changes in a way clients must know about. */
            api_level: number;
        };
        WhoAmI: {
            key: {
                id: string;
                name: string;
                /** @description The start of the key, for telling keys apart. Never the key. */
                prefix: string;
                /** @enum {string} */
                scope: "account" | "service";
            };
            /** @description Who an account key acts as. Left out for a service key. */
            user?: {
                id: string;
                email: string;
                display_name?: string;
            };
        };
        JobSummary: {
            slug: string;
            name: string;
            description?: string;
            /** @description Workers serving this queue run it. */
            queue: string;
            /** @description The image its command runs in. */
            runtime: string;
            last_run?: components["schemas"]["Run"];
        };
        /**
         * @example {
         *       "slug": "web-release",
         *       "name": "Web release",
         *       "description": "Build and ship the web app",
         *       "queue": "deploy",
         *       "runtime": "node:25-alpine",
         *       "command": "./scripts/ship.sh",
         *       "parameters": [
         *         {
         *           "name": "environment",
         *           "type": "select",
         *           "label": "Environment",
         *           "env_var": "ENVIRONMENT",
         *           "required": true,
         *           "options": [
         *             {
         *               "value": "staging",
         *               "label": "Staging"
         *             },
         *             {
         *               "value": "prod",
         *               "label": "Production"
         *             }
         *           ]
         *         },
         *         {
         *           "name": "dry_run",
         *           "type": "bool",
         *           "label": "Dry run",
         *           "env_var": "DRY_RUN",
         *           "required": false,
         *           "default": false
         *         }
         *       ]
         *     }
         */
        JobDetail: components["schemas"]["JobSummary"] & {
            command: string;
            /** @description Git URL checked out into the workspace. */
            source_repo?: string;
            parameters: components["schemas"]["Parameter"][];
        };
        Parameter: {
            /** @description The key to use in `params`. */
            name: string;
            /** @enum {string} */
            type: "string" | "number" | "bool" | "select" | "multiselect" | "date" | "datetime" | "secret";
            label?: string;
            /** @description The environment variable the value reaches the job as. */
            env_var: string;
            description?: string;
            required: boolean;
            /** @description Used when the value is left out. Never set for a secret. */
            default?: unknown;
            /** @description The allowed values of a `select` or `multiselect`. */
            options?: {
                value: string;
                label?: string;
                hint?: string;
            }[];
        };
        StartRunRequest: {
            /**
             * @description Values keyed by parameter name. A `multiselect` takes an array; a `number` or `bool` may
             *     also be a string. Left-out values take their default.
             */
            params?: {
                [key: string]: unknown;
            };
        };
        CreateRunRequest: {
            /** @description Only workers serving this queue pick the run up. */
            queue: string;
            /**
             * @description `container` runs an image; `noop` succeeds without doing anything.
             * @enum {string}
             */
            type: "container" | "noop";
            payload?: components["schemas"]["ContainerPayload"];
            /** @description Worker labels the run needs. */
            selector?: {
                [key: string]: string;
            };
            /** @description Stop the job after this many seconds. */
            timeout_sec?: number;
            /** @description How many times to try again after a failure. */
            max_retries?: number;
            /** @description Hold the run back this long before a worker can take it. */
            delay_ms?: number;
            /** @description Ordering within the queue. */
            priority?: number;
            /** @description Send it again and you get the first run back instead of a second one. */
            idempotency_key?: string;
            webhook?: components["schemas"]["Webhook"];
        };
        /** @description Input for the `container` handler. */
        ContainerPayload: {
            /** @description Image to run, e.g. `node:25-alpine`. */
            runtime?: string;
            /** @description Shell command inside it. */
            command?: string;
            /** @description Environment variables, name → value. */
            request_params?: {
                [key: string]: string;
            };
            /** @description Git URL checked out into the workspace. */
            source_repository?: string;
        };
        Webhook: {
            /** Format: uri */
            url: string;
            /** @description Signing secret. Left out, one is generated and returned once as `webhook_secret`. */
            secret?: string;
            /** @description Defaults to `run.completed` and `run.failed`. */
            events?: ("run.started" | "run.completed" | "run.failed")[];
        };
        /**
         * @example {
         *       "id": "66fb1c2d3e4f5a6b7c8d9e0f",
         *       "queue": "deploy",
         *       "type": "container",
         *       "status": "running",
         *       "attempts": 1,
         *       "max_retries": 2,
         *       "timeout_sec": 900,
         *       "worker_id": "66f9e0a1c4b2d3e4f5a6b7c8",
         *       "idempotency_key": "release-2026-09-30",
         *       "webhook_url": "https://ci.example.com/hooks/lute",
         *       "webhook_events": [
         *         "run.completed",
         *         "run.failed"
         *       ],
         *       "enqueued_at": "2026-09-30T09:14:02Z",
         *       "started_at": "2026-09-30T09:14:03Z"
         *     }
         */
        Run: {
            /** @description 24 hex characters. The first 8 are the short form, `#66fb1c2d`. */
            id: string;
            /** @description The job's slug, for a run started from a job. */
            job?: string;
            /** @description The values a job run got, keyed by env var. Secrets are never included. */
            params?: {
                [key: string]: string;
            };
            queue: string;
            type: string;
            status: components["schemas"]["RunStatus"];
            priority?: number;
            attempts: number;
            max_retries: number;
            timeout_sec: number;
            /** @description Last failure, if any. */
            error?: string;
            /** @description Set once a worker leased the run. */
            worker_id?: string;
            idempotency_key?: string;
            webhook_url?: string;
            webhook_events?: string[];
            /** Format: date-time */
            enqueued_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            elapsed_ms?: number;
        };
        CreatedRun: components["schemas"]["Run"] & {
            /** @description The generated webhook secret, returned once. */
            webhook_secret?: string;
        };
        /**
         * @description `pending` until a worker takes it, then `running`. `done` and `failed` are final; `dead`
         *     means it ran out of retries or was cancelled.
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "done" | "failed" | "dead" | "unknown";
        RunList: {
            runs: components["schemas"]["Run"][];
            total: number;
            offset: number;
            limit: number;
        };
        LogPage: {
            lines: string[];
            /** @enum {string} */
            direction: "tail" | "head";
            has_more: boolean;
            /** @description Bytes. */
            file_size: number;
            /** @description Pass as `cursor` for the next page. */
            next_cursor?: string;
            /** @description A problem the worker hit reading the file; the page is still valid. */
            error?: string;
        };
        /** @enum {string} */
        WorkerStatus: "pending" | "registered" | "alive" | "dead" | "deleting";
        /**
         * @example {
         *       "id": "66f9e0a1c4b2d3e4f5a6b7c8",
         *       "created_at": "2026-09-12T18:02:44.120Z",
         *       "updated_at": "2026-09-30T09:15:40.412Z",
         *       "name": "ci-rootless-01",
         *       "description": "",
         *       "status": "alive",
         *       "agent_version": "0.2.0",
         *       "protocol": 2,
         *       "engine": {
         *         "kind": "docker",
         *         "version": "28.4.0",
         *         "rootless": true,
         *         "memory_limit": true,
         *         "cpu_limit": true,
         *         "pids_limit": true
         *       },
         *       "last_seen": "2026-09-30T09:15:40.412Z",
         *       "labels": {
         *         "arch": "amd64",
         *         "os": "linux"
         *       }
         *     }
         */
        Worker: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            name: string;
            description?: string;
            status: components["schemas"]["WorkerStatus"];
            agent_version?: string;
            protocol?: number;
            engine?: components["schemas"]["Engine"];
            /** Format: date-time */
            last_seen?: string;
            metrics?: {
                [key: string]: unknown;
            };
            labels?: {
                [key: string]: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
            /** @description The agent is older than core; pull the image. */
            outdated?: boolean;
        };
        /** @description The container engine the worker runs jobs on, as the agent reported it. */
        Engine: {
            kind?: string;
            version?: string;
            rootless?: boolean;
            memory_limit?: boolean;
            cpu_limit?: boolean;
            pids_limit?: boolean;
        };
        ConnectedWorker: {
            worker_id: string;
            queues: string[];
            concurrency: number;
            active_jobs: number;
            draining: boolean;
        };
        Labels: {
            /** @description Up to 32. Keys are 1–63 letters, digits, `_`, `-` or `.`. */
            labels: {
                [key: string]: string;
            };
        };
        DeleteResult: {
            /** @enum {string} */
            status: "deleted" | "deleting";
            message?: string;
        };
        /** @enum {string} */
        CommandStatus: "pending" | "running" | "completed" | "failed";
        /**
         * @example {
         *       "id": "66fa2b0c1d2e3f4a5b6c7d8e",
         *       "created_at": "2026-09-30T09:18:02.310Z",
         *       "updated_at": "2026-09-30T09:18:02.940Z",
         *       "worker_id": "66f9e0a1c4b2d3e4f5a6b7c8",
         *       "command": "df",
         *       "args": [
         *         "-h",
         *         "/var/lib/lute-worker"
         *       ],
         *       "status": "completed",
         *       "output": "Filesystem  Size  Used Avail Use% Mounted on\n/dev/sda1   98G   31G   62G  34% /var/lib/lute-worker\n",
         *       "exit_code": 0
         *     }
         */
        Command: {
            id: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            worker_id: string;
            command: string;
            args?: string[];
            env?: {
                [key: string]: string;
            };
            status: components["schemas"]["CommandStatus"];
            output?: string;
            exit_code: number;
            error?: string;
        };
        /**
         * @example {
         *       "id": "66fa2c7d8e9f0a1b2c3d4e5f",
         *       "created_at": "2026-09-30T09:20:11.052Z",
         *       "updated_at": "2026-09-30T09:31:48.600Z",
         *       "name": "build-farm",
         *       "prefix": "lute_rt_K3M9QX",
         *       "created_by": "66f1a2b3c4d5e6f7a8b9c0d1",
         *       "last_used_at": "2026-09-30T09:31:48.600Z"
         *     }
         */
        RegistrationToken: {
            id: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            name: string;
            /** @description The start of the token, for telling tokens apart. */
            prefix: string;
            created_by: string;
            /** Format: date-time */
            last_used_at?: string;
            /** Format: date-time */
            revoked_at?: string;
        };
        CreatedToken: components["schemas"]["RegistrationToken"] & {
            /** @description The plaintext token. Shown once. */
            token: string;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "unavailable" | "internal";
                message: string;
                /** @description Per-input messages, for `validation_failed`. */
                fields?: {
                    [key: string]: string;
                };
            };
        };
    };
    responses: {
        /** @description The request is invalid. `error.fields` names each bad input when there is one. */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "validation_failed",
                 *         "message": "webhook.url is required when webhook is provided",
                 *         "fields": {
                 *           "webhook.url": "required"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, unknown or revoked API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "invalid API key"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found, or not yours. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "not_found",
                 *         "message": "run not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with the current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "conflict",
                 *         "message": "can only cancel pending jobs, status is running"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description The run's `id`, or a prefix of it of at least 8 characters.
         * @example 66fb1c2d
         */
        RunID: string;
        /**
         * @description The job's `slug`.
         * @example web-release
         */
        JobSlug: string;
        /**
         * @description The worker's `id`.
         * @example 66f9e0a1c4b2d3e4f5a6b7c8
         */
        WorkerID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server's version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": "0.2.0",
                     *       "api_level": 1
                     *     }
                     */
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    whoAmI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The key, and the user an account key acts as. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "key": {
                     *         "id": "66fb0a1b2c3d4e5f6a7b8c9d",
                     *         "name": "laptop",
                     *         "prefix": "lute_sk_k3m9qxab",
                     *         "scope": "account"
                     *       },
                     *       "user": {
                     *         "id": "66f1a2b3c4d5e6f7a8b9c0d1",
                     *         "email": "anton@acme.dev"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "jobs": [
                     *         {
                     *           "slug": "web-release",
                     *           "name": "Web release",
                     *           "description": "Build and ship the web app",
                     *           "queue": "deploy",
                     *           "runtime": "node:25-alpine",
                     *           "last_run": {
                     *             "id": "66fb1c2d3e4f5a6b7c8d9e0f",
                     *             "job": "web-release",
                     *             "queue": "deploy",
                     *             "type": "container",
                     *             "status": "done",
                     *             "attempts": 1,
                     *             "max_retries": 3,
                     *             "timeout_sec": 300,
                     *             "enqueued_at": "2026-09-30T09:14:02Z"
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        jobs: components["schemas"]["JobSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The job's `slug`.
                 * @example web-release
                 */
                slug: components["parameters"]["JobSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    startJobRun: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Send it again and you get the first run back instead of a second one.
                 * @example release-2026-09-30
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description The job's `slug`.
                 * @example web-release
                 */
                slug: components["parameters"]["JobSlug"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "params": {
                 *         "environment": "staging",
                 *         "regions": [
                 *           "eu-central",
                 *           "us-east"
                 *         ],
                 *         "dry_run": true
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description A run with this `Idempotency-Key` already exists; it is returned unchanged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run started. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "66fb1c2d3e4f5a6b7c8d9e0f",
                     *       "job": "web-release",
                     *       "params": {
                     *         "ENVIRONMENT": "staging",
                     *         "REGIONS": "eu-central,us-east",
                     *         "DRY_RUN": "true"
                     *       },
                     *       "queue": "deploy",
                     *       "type": "container",
                     *       "status": "pending",
                     *       "attempts": 0,
                     *       "max_retries": 3,
                     *       "timeout_sec": 300,
                     *       "enqueued_at": "2026-09-30T09:14:02Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Only runs of this job's slug. */
                job?: string;
                /** @description Only runs in this status. */
                status?: components["schemas"]["RunStatus"];
                /** @description Only runs on this queue. */
                queue?: string;
                /** @description Only runs of this type. */
                type?: string;
                /** @description Runs to skip. */
                offset?: number;
                /** @description Runs to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "runs": [
                     *         {
                     *           "id": "66fb1c2d3e4f5a6b7c8d9e0f",
                     *           "job": "web-release",
                     *           "params": {
                     *             "ENVIRONMENT": "staging"
                     *           },
                     *           "queue": "deploy",
                     *           "type": "container",
                     *           "status": "done",
                     *           "attempts": 1,
                     *           "max_retries": 0,
                     *           "timeout_sec": 0,
                     *           "worker_id": "66f9e0a1c4b2d3e4f5a6b7c8",
                     *           "enqueued_at": "2026-09-30T09:14:02Z",
                     *           "started_at": "2026-09-30T09:14:03Z",
                     *           "finished_at": "2026-09-30T09:15:41Z",
                     *           "elapsed_ms": 98214
                     *         }
                     *       ],
                     *       "total": 1,
                     *       "offset": 0,
                     *       "limit": 50
                     *     }
                     */
                    "application/json": components["schemas"]["RunList"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "queue": "deploy",
                 *       "type": "container",
                 *       "payload": {
                 *         "runtime": "node:25-alpine",
                 *         "command": "./scripts/ship.sh",
                 *         "request_params": {
                 *           "ENVIRONMENT": "staging"
                 *         }
                 *       },
                 *       "selector": {
                 *         "region": "eu"
                 *       },
                 *       "idempotency_key": "release-2026-09-30",
                 *       "webhook": {
                 *         "url": "https://ci.example.com/hooks/lute"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description A run with this `idempotency_key` already exists; it is returned unchanged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "66fb1c2d3e4f5a6b7c8d9e0f",
                     *       "queue": "deploy",
                     *       "type": "container",
                     *       "status": "pending",
                     *       "attempts": 0,
                     *       "max_retries": 0,
                     *       "timeout_sec": 0,
                     *       "idempotency_key": "release-2026-09-30",
                     *       "webhook_url": "https://ci.example.com/hooks/lute",
                     *       "webhook_events": [
                     *         "run.completed",
                     *         "run.failed"
                     *       ],
                     *       "enqueued_at": "2026-09-30T09:14:02Z",
                     *       "webhook_secret": "9c1e4f0b7a2d…"
                     *     }
                     */
                    "application/json": components["schemas"]["CreatedRun"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The run's `id`, or a prefix of it of at least 8 characters.
                 * @example 66fb1c2d
                 */
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The run's `id`, or a prefix of it of at least 8 characters.
                 * @example 66fb1c2d
                 */
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cancelled run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    retryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The run's `id`, or a prefix of it of at least 8 characters.
                 * @example 66fb1c2d
                 */
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run, queued again. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRunLogs: {
        parameters: {
            query?: {
                /** @description `tail` pages back from the end, `head` forward from the start. */
                direction?: "tail" | "head";
                /** @description Lines per page. */
                limit?: number;
                /** @description `next_cursor` of the previous page. */
                cursor?: string;
            };
            header?: never;
            path: {
                /**
                 * @description The run's `id`, or a prefix of it of at least 8 characters.
                 * @example 66fb1c2d
                 */
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of log lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "lines": [
                     *         "> ship@1.0.0 build",
                     *         "vite v7 building for production...",
                     *         "✓ built in 4.12s"
                     *       ],
                     *       "direction": "tail",
                     *       "has_more": true,
                     *       "file_size": 48213,
                     *       "next_cursor": "46980"
                     *     }
                     */
                    "application/json": components["schemas"]["LogPage"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The worker that holds the log is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listWorkers: {
        parameters: {
            query?: {
                /** @description `key:value`; repeat it to require several labels. */
                label?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listConnectedWorkers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The connected workers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "workers": [
                     *         {
                     *           "worker_id": "66f9e0a1c4b2d3e4f5a6b7c8",
                     *           "queues": [
                     *             "default",
                     *             "deploy"
                     *           ],
                     *           "concurrency": 4,
                     *           "active_jobs": 1,
                     *           "draining": false
                     *         }
                     *       ],
                     *       "count": 1
                     *     }
                     */
                    "application/json": {
                        workers: components["schemas"]["ConnectedWorker"][];
                        count: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getInstallInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Install details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "server": "lute.example.com:50051",
                     *       "image": "ghcr.io/notna-k/lute-worker:0.2"
                     *     }
                     */
                    "application/json": {
                        /** @description core's gRPC address, `host:port`. */
                        server: string;
                        /** @description Worker image to run. */
                        image: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWorker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The worker. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWorker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "ci-rootless-03",
                 *       "description": "Build farm, rack B"
                 *     }
                 */
                "application/json": {
                    /** @description 1–63 letters, digits, `.`, `_` or `-`, starting with a letter or digit. Unique across Lute. */
                    name?: string;
                    description?: string;
                };
            };
        };
        responses: {
            /** @description The updated worker. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteWorker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "deleted"
                     *     }
                     */
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Draining; removed once its running jobs finish. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "deleting",
                     *       "message": "The worker finishes its running jobs, then stops."
                     *     }
                     */
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getWorkerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live status. Version, last seen and metrics appear once the agent has reported. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "worker_id": "66f9e0a1c4b2d3e4f5a6b7c8",
                     *       "name": "ci-rootless-01",
                     *       "status": "alive",
                     *       "agent_version": "0.2.0",
                     *       "last_seen": "2026-09-30T09:15:40.412Z",
                     *       "metrics": {
                     *         "cpu_load": 0.42,
                     *         "mem_usage_mb": 12.4,
                     *         "disk_used_gb": 31.2,
                     *         "disk_total_gb": 98
                     *       }
                     *     }
                     */
                    "application/json": {
                        worker_id: string;
                        name: string;
                        status: components["schemas"]["WorkerStatus"];
                        agent_version?: string;
                        /** Format: date-time */
                        last_seen?: string;
                        metrics?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getWorkerLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The worker's labels. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "labels": {
                     *         "arch": "amd64",
                     *         "os": "linux"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Labels"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    setWorkerLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "labels": {
                 *         "arch": "amd64",
                 *         "os": "linux",
                 *         "region": "eu"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Labels"];
            };
        };
        responses: {
            /** @description The updated worker. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    reEnableWorker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The worker, now pending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"];
                };
            };
            /** @description The worker is not dead. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCommands: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The commands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        commands: components["schemas"]["Command"][];
                        count: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    sendCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The worker's `id`.
                 * @example 66f9e0a1c4b2d3e4f5a6b7c8
                 */
                id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "command": "df",
                 *       "args": [
                 *         "-h",
                 *         "/var/lib/lute-worker"
                 *       ]
                 *     }
                 */
                "application/json": {
                    command: string;
                    args?: string[];
                    env?: {
                        [key: string]: string;
                    };
                };
            };
        };
        responses: {
            /** @description Queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "command_id": "66fa2b0c1d2e3f4a5b6c7d8e",
                     *       "status": "pending",
                     *       "message": "Command queued for worker"
                     *     }
                     */
                    "application/json": {
                        command_id: string;
                        status: components["schemas"]["CommandStatus"];
                        message: string;
                    };
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCommandResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description `command_id` from Send a command.
                 * @example 66fa2b0c1d2e3f4a5b6c7d8e
                 */
                commandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The command, with its output once it finished. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Command"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every registration token, newest first and revoked ones included. Tokens are shared by all operators. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tokens: components["schemas"]["RegistrationToken"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "build-farm"
                 *     }
                 */
                "application/json": {
                    /** @description What the token is for. */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "66fa2c7d8e9f0a1b2c3d4e5f",
                     *       "created_at": "2026-09-30T09:20:11.052Z",
                     *       "updated_at": "2026-09-30T09:20:11.052Z",
                     *       "name": "build-farm",
                     *       "prefix": "lute_rt_K3M9QX",
                     *       "created_by": "66f1a2b3c4d5e6f7a8b9c0d1",
                     *       "token": "lute_rt_K3M9QX…"
                     *     }
                     */
                    "application/json": components["schemas"]["CreatedToken"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The token's `id`.
                 * @example 66fa2c7d8e9f0a1b2c3d4e5f
                 */
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
